---
title: "Chapter Six Assignment"
author: "John K. Hancock"
date: "October 30, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Chapter Six Homework Assigments


6.6 2010 Healthcare Law. On June 28, 2012 the U.S. Supreme Court upheld the much debated
2010 healthcare law, declaring it constitutional. A Gallup poll released the day after this decision
indicates that 46% of 1,012 Americans agree with this decision. At a 95% confidence level, this
sample has a 3% margin of error. Based on this information, determine if the following statements
are true or false, and explain your reasoning.39



(a) We are 95% confident that between 43% and 49% of Americans in this sample support the
decision of the U.S. Supreme Court on the 2010 healthcare law.
(b) We are 95% confident that between 43% and 49% of Americans support the decision of the
U.S. Supreme Court on the 2010 healthcare law.
(c) If we considered many random samples of 1,012 Americans, and we calculated the sample
proportions of those who support the decision of the U.S. Supreme Court, 95% of those sample
proportions will be between 43% and 49%.
(d) The margin of error at a 90% confidence level would be higher than 3%.